### ISSUE TITLE
i have no text

### ISSUE THREAD

**Issue by dinolover** [FossilsArcheologyRevival/FossilArcheology#215]
when i receive text from the mod, no matter what text it is it just doesn't appear, all it is, is a blank text box with no writing. it is hard to control my dinos like this because i don't know if they are free moving, staying, or following me. i was watching a YouTuber and his text was fine. every single message is missing, when my dinos are full, when the chicken essence has no use, when they learn chest etc. i hope you can help, thank you if you can.

**Comment by lalaladinosaur** [comment]
If I change my name for mc, will I atill have my dinos as mine? Ik ur
awfully busy but plz let me know -lalaladinosaur

**Comment by JTGhawk137** [comment]
You should keep it, considering everything is UUID based.
