### ISSUE TITLE
AI

### ISSUE THREAD

**Issue by SteveOriginal** [FossilsArcheologyRevival/FossilArcheology#375]
Since The Recession Flight Of Skill Do Pterosaur This Group Was Not Valued They should Add Quetzalcoatlus, Nyctosaurus ... Another suggestion would be Just A Short Bat Modification Do not Be So What So Advanced.

**Comment by JTGhawk137** [comment]
English plz?

**Comment by PCAwesomeness** [comment]
Nobody wants to have a simple bat AI.

Can we close this?
